// teams.js
export const TEAMS = [
    { id: "/g/121qfk5v", name: "Thanh Hóa", stadium: "Sân vận động Thanh Hóa, 37 Lê Quý Đôn, P. Ba Đình, Thạnh Hóa, Thanh Hoá, Việt Nam" },
    { id: "/m/0ghqgf", name: "Hoàng Anh Gia Lai", stadium: "Sân vận động Pleiku, Quang Trung, P.Tây Sơn, Pleiku, Gia Lai 600000, Việt Nam" },
    { id: "/g/11f08kzdh8", name: "Hồng Lĩnh Hà Tĩnh", stadium: "Sân vận động Hà Tĩnh, Nguyễn Biểu, Nam Hà, Hà Tĩnh, Việt Nam" },
    { id: "/m/01xn5sc", name: "Bình Dương", stadium: "Sân vận động Gò Đậu, Đ. 30 Tháng 4, Phú Thọ, Thủ Dầu Một, Bình Dương, Việt Nam" },
    { id: "/m/0ghqfd", name: "Nam Định", stadium: "Sân vận động Thiên Trường, 5 Đặng Xuân Thiều, Vị Hoàng, Nam Định, Việt Nam" },
    { id: "/m/064l6nx", name: "Hà Nội", stadium: "Sân vận động Hàng Đẫy, 9 P. Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội, Việt Nam" },
    { id: "/m/051x467", name: "Viettel", stadium: "Sân Vận Động Mỹ Đình, Mỹ Đình 1, Nam Từ Liêm, Hà Nội, Việt Nam" },
    { id: "/g/1228xg3s", name: "CAHN", stadium: "Sân vận động Hàng Đẫy, 9 P. Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội, Việt Nam" },
    { id: "/m/09k53c6", name: "Quảng Nam", stadium: "Sân Vận Động Hòa Xuân, Dương Loan, Hoà Xuân, Cẩm Lệ, Đà Nẵng 550000, Việt Nam" },
    { id: "/m/01xn5sr", name: "TP.HCM", stadium: "Sân vận động Thống Nhất, 138 Đ. Đào Duy Từ, Phường 6, Quận 10, Hồ Chí Minh, Việt Nam" },
    { id: "/m/0ghqdc", name: "Bình Định", stadium: "Sân vận động Quy Nhơn, 194 Lê Hồng Phong, Trần Hưng Đạo, Quy Nhơn, Bình Định, Việt Nam" },
    { id: "/m/0404qjd", name: "Hải Phòng", stadium: "Sân vận động Lạch Tray, 15 Lạch Tray, Lê Lợi, Ngô Quyền, Hải Phòng 180000, Việt Nam" },
    { id: "/m/026hmd8", name: "Đà Nẵng", stadium: "Sân vân động Hòa Xuân, Trần Nam Trung, Hoà Xuân, Cẩm Lệ, Đà Nẵng 550000, Việt Nam" },
    { id: "/m/0ghqf1", name: "Sông Lam Nghệ An", stadium: "Sân Vận động Vinh, Đào Tấn, Cửa Nam, Vinh, Nghệ An, Việt Nam" },
    { id: "/m/04ltf", name: "Liverpool", stadium: "Sân vận động Anfield, Anfield Rd, Anfield, Liverpool L4 0TH, Vương Quốc Anh" },
    { id: "/m/01634x", name: "Man City", stadium: "Sân vận động Thành phố Manchester, Etihad Stadium, Etihad Campus, Manchester M11 3FF, Vương Quốc Anh" },
    { id: "/m/0xbm", name: "Arsenal", stadium: "Emirates Stadium, Hornsey Rd, London N7 7AJ, Vương Quốc Anh" },
    { id: "/m/0bl8l", name: "Aston Villa", stadium: "Sân vận động Villa Park, Trinity Rd, Birmingham B6 6HE, Vương Quốc Anh" },
    { id: "/m/0j2pg", name: "Brighton", stadium: "American Express Stadium, Village Way, Brighton and Hove, Brighton BN1 9BL, Vương Quốc Anh" },
    { id: "/m/023fb", name: "Chelsea", stadium: "Sân vận động Stamford Bridge, Fulham Rd., London SW6 1HS, Vương Quốc Anh" },
    { id: "/m/0hvjr", name: "Tottenham", stadium: "Sân vận động Tottenham Hotspur, 782 High Rd, London N17 0BX, Vương Quốc Anh" },
    { id: "/m/014nzp", name: "Nottm Forest", stadium: "The City Ground, West Bridgford, Nottingham NG2 5FJ, Vương Quốc Anh" },
    { id: "/m/0fvly", name: "Newcastle", stadium: "St. James' Park, Barrack Rd, Newcastle upon Tyne NE1 4ST, Vương Quốc Anh" },
    { id: "/m/02_lt", name: "Fulham", stadium: "Sân vận động Craven Cottage, Stevenage Rd, London SW6 6HH, Vương Quốc Anh" },
    { id: "/m/02b0xq", name: "Bournemouth", stadium: "Vitality Stadium, Kings Park, Bournemouth BH7 7AF, Vương Quốc Anh" },
    { id: "/m/050fh", name: "Man Utd", stadium: "Sân vận động Old Trafford, Sir Matt Busby Way, Old Trafford, Stretford, Manchester M16 0RA, Vương Quốc Anh" },
    { id: "/m/02b0y3", name: "Brentford", stadium: "Gtech Community Stadium, Lionel Rd S, Brentford TW8 0RU, Vương Quốc Anh" },
    { id: "/m/01rlzn", name: "Leicester", stadium: "Sân vận động King Power, Filbert Wy, Leicester LE2 7FL, Vương Quốc Anh" },
    { id: "/m/0ckf6", name: "West Ham", stadium: "Sân vận động Olympic, Luân Đôn E20 2ST, Vương Quốc Anh" },
    { id: "/m/0mmd6", name: "Everton", stadium: "Sân vận động Goodison Park, Goodison Rd, Liverpool L4 4EL, Vương Quốc Anh" },
    { id: "/m/01zhs3", name: "Ipswich Town", stadium: "Portman Road Stadium, Town Football Club, Portman Rd, Ipswich IP1 2DA, Vương Quốc Anh" },
    { id: "/m/0223bl", name: "Crystal Palace", stadium: "Selhurst Park Stadium, Holmesdale Rd, London SE25 6PU, Vương Quốc Anh" },
    { id: "/m/0k_l4", name: "Southampton", stadium: "St Mary's Stadium, Britannia Rd, Southampton SO14 5FP, Vương Quốc Anh" },
    { id: "/m/01fwqn", name: "Wolves", stadium: "Molineux Stadium, Waterloo Rd, Wolverhampton WV1 4QR, Vương Quốc Anh" },
    { id: "/m/04b6sy", name: "Việt Nam", stadium: "Sân vận động Quốc gia Mỹ Đình, 1 Đ. Lê Đức Thọ, Mỹ Đình, Nam Từ Liêm, Hà Nội, Việt Nam" },
    { id: "/m/046vvc", name: "Thái Lan", stadium: "Rajamangala National Stadium, 286 Soi Ramkhamhaeng 24 Yaek 18, Khwaeng Hua Mak, Khet Bang Kapi, Krung Thep Maha Nakhon 10240, Thái Lan" },
    { id: "/m/0413b_", name: "Indonesia", stadium: "Sân vận động Bung Karno, Jl. Pintu Satu Senayan, Gelora, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10270, Indonesia" },
    { id: "/m/04h4zx", name: "Malaysia", stadium: "Sân vận động quốc gia Bukit Jalil, Jalan Barat, Bukit Jalil, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia" },
    { id: "/m/04h54p", name: "Singapore", stadium: "Sân vận động quốc gia Singapore, 1 Stadium Dr, Singapore 397629" },
    { id: "/m/04k3r_", name: "Philippines", stadium: "Sân vận động Rizal Memorial, Rizal Memorial Sports Complex, Adriatico St, Malate, Maynila, 1004 Kalakhang Maynila, Philippines" },
    { id: "/m/04nq_y", name: "Lào", stadium: "Sân vận động Quốc gia Lào Mới, 18°03'43.7\"N 102°42'14., 2E, Muang Xai, Lào" },
    { id: "/m/04nqn6", name: "Campuchia", stadium: "Sân vận động Olympic, Charles de Gaulle Boulevard រាជធានី​ភ្នំពេញ, Phnom Penh 12253, Campuchia" },
    { id: "/m/04q41k", name: "Myanmar", stadium: "Sân vận động Thuwunna, R5CP+GPG, Ragoon, Myanmar (Miến Điện)" },
    { id: "/m/04mx79", name: "Đông Timor", stadium: "9 P. Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội, Việt Nam" },
    { id: "/g/11b6nyv4yk", name: "Bình Phước", stadium: "Sân vận động tỉnh Bình Phước, GVHH+HFM, Tân Bình, Đồng Xoài, Bình Phước, Việt Nam" },
    { id: "/g/11f1zdmlfs", name: "Ninh Bình", stadium: "Sân vận động Đông Thành, Đông Phương Hồng, Đông Thành, Ninh Bình, Việt Nam" },
    { id: "/m/06l22", name: "Real Madrid", stadium: "Sân vận động Santiago Bernabéu, Av. de Concha Espina, 1, Chamartín, 28036 Madrid, Tây Ban Nha" },
    { id: "/m/0hvgt", name: "Barcelona", stadium: "Sân vận động Camp Nou, Les Corts, 08028 Barcelona, Tây Ban Nha" },
    { id: "/m/02w64f", name: "Tây Ban Nha", stadium: "Sân vận động Santiago Bernabéu, Av. de Concha Espina, 1, Chamartín, 28036 Madrid, Tây Ban Nha" },
    { id: "/m/01l3vx", name: "Pháp", stadium: "Stade de France, 93200 Saint-Denis, Pháp" },
    { id: "/m/01l3wr", name: "Đức", stadium: "Sân vận động Allianz, Werner-Heisenberg-Allee 25, 80939 München, Đức" },
    { id: "/m/02rqxc", name: "Bồ Đào Nha", stadium: "Estádio do Sport Lisboa e Benfica, Av. Eusébio da Silva Ferreira, 1500-313 Lisboa, Bồ Đào Nha" },
    { id: "/m/01_1kk", name: "PSG", stadium: "Parc des Princes, 24 Rue du Commandant Guilbaud, 75016 Paris, Pháp" },
    { id: "/m/03x6m", name: "Inter", stadium: "Sân vận động Giuseppe Meazza, Piazzale Angelo Moratti, 20151 Milano MI, Ý" }
  ];