/**
 * Danh sách các câu trích dẫn triết lý truyền cảm hứng
 */
export const quoteTrietLy = [
  "Hãy là chính mình, mọi người khác đã có người đóng rồi. – Oscar Wilde",
  "Bạn trở thành điều bạn nghĩ đến nhiều nhất. – Earl Nightingale",
  "Sự thay đổi bắt đầu từ chính bạn. – Mahatma Gandhi",
  "Cuộc sống là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng với nó. – Charles R. Swindoll",
  "Không gì là không thể, chính từ đó cũng nói rằng: 'I'm possible!' – Audrey Hepburn",
];

/**
 * Danh sách các câu trích dẫn hài hước, vui vẻ
 */
export const quoteHaiHuoc = [
  "Người ta giận dỗi thì bỏ cơm, còn tôi giận dỗi thì bỏ đầy 2 bát liền!",
  "Tôi rửa mặt xong bị xước hết cả tay, đúng thật là hoa hồng đẹp luôn có gai.",
  "Tôi hỏi chiếc quạt điện rằng tôi có xấu không, ai ngờ nó lắc đầu cả đêm.",
  "Bạn muốn người yêu ngồi đối diện hay là ngồi cạnh? Tôi thì thích họ ngồi xung quanh.",
  "Càng lớn, tôi lại càng thấy mình nhiều tuổi.",
  "Bây giờ bạn chỉ muốn mắng tôi tức là bạn đang không hiểu tôi, nhưng sau khi hiểu tôi rồi, chắc bạn sẽ vừa mắng vừa đánh.",
  "Người ta nói người phụ nữ bên cạnh mình giống như quần áo. Nhìn lại, tôi đã khỏa thân chạy khắp nơi trong 20 năm!",
  "Đừng sợ kẻ thù như hổ, mà hãy sợ đồng đội như lợn.",
  "Chuyện gì lúc bắt đầu chẳng khó, tới giữa vẫn khó, đến cuối còn khó hơn.",
  "Bạn không hài lòng về điều gì? Hãy kể ra để mọi người cùng vui.",
  "Ăn không đủ thì làm sao giảm cân được?",
  "Mẹo tiết kiệm thời gian: để dành 2 chuyện buồn rồi mới khóc.",
  "Bạn bảo mời tôi trà sữa khi nhận lương. Lâu lắm rồi không thấy bạn, chắc bị đuổi việc rồi hả?",
  "Tôi: Trời hôm nay xấu vậy. Trời: Chắc bà đẹp!",
  "Muốn đi xa thì đi một mình, muốn đi chung thì đi cùng nhau.",
  "Ai bảo tôi chẳng có gì? Ít nhất tôi còn có bệnh cơ mà!",
  "Khi Thượng Đế đóng một cánh cửa của bạn, người sẽ tiện tay dùng nó kẹp đầu bạn luôn.",
  "Tôi đã tìm thấy lối thoát trong công việc: thoát vị đĩa đệm.",
  "Trời cho tôi gương mặt đẹp, nhưng lại lấy đi người công nhận điều đó.",
  "Hoàng hôn có đẹp đến mấy cũng chỉ là buổi chiều tà.",
  "Tôi có chồng rồi. Chồng… bát chưa rửa trong bếp.",
  "Cách để không bị lợi dụng: trở nên vô dụng.",
  "Đói quá đi mất! Sắc đẹp thật là không mài ra ăn được mà.",
  "Bố tôi lái BMW, mẹ tôi đi Porsche, còn tôi thì bốc phét.",
  "Đừng thức đêm nhiều, rất có hại cho điện thoại đấy!",
  "Tôi tự nhủ phải cố gắng hết mình, để người ta không phàn nàn tôi ngoài đẹp ra thì chẳng còn gì khác.",
  "Bật mí cho bạn một điều, không có khó khăn nào không đánh gục được tôi cả.",
  "Hy vọng mọi người hãy nói cho tôi biết khuyết điểm của mình, có gì nói đó, không sao đâu, tôi vừa block 5 người bạn rồi.",
  "Hôm nay, tôi đến bệnh viện kiểm tra sức khỏe. Bác sĩ hỏi tôi: Uống rượu không? Tôi đáp: Bây giờ ư?",
  "Nghe nói người đẹp thường chỉ nói chuyện nửa câu, không biết là…",
  "Đừng nói xấu người khác với tôi, nếu không thì tôi cũng muốn nói theo đó.",
  "Bạn nào đi châu Âu rồi cho mình hỏi chút, tiền đâu ra mà đi vậy?",
  "Một người đơn giản như tôi không thể giải quyết được vấn đề phức tạp như vậy.",
  "Tết sắp đến, mình còn khoản nợ mấy trăm triệu cần pass lại cho ai có thiện chí.",
  "Em ơi trời lạnh lắm! Đi đâu nhớ mang theo anh.",
  "Dạo này mình hết thức khuya rồi, mình thức tới sáng luôn.",
  "Hôm nay cô đơn một chút cũng không sao, đằng nào ngày mai cũng vậy mà.",
  "Giang sơn dễ đổi. Tính em dễ thương.",
  "Ai cũng nghĩ tôi có người thương, làm tôi cũng tưởng vậy.",
  "Nhiều lúc thấy bản thân hơi quá đáng… yêu.",
  "Nhìn mình hiền lành vậy thôi, chứ thực ra mình hiền thật.",
  "Đừng mải hít drama nữa, hít mình nè cậu ơi.",
  "Đừng trì hoãn việc đến ngày mai. Ngày kia làm cũng được.",
  "Nghèo cho sạch. Rách… thì vá lại.",
  "Lửa thử vàng, gian nan thì nghỉ việc.",
  "Tiền là gì? Đó là thứ mà tôi không có.",
  "Nếu phải trả phí để hít thở, có lẽ tôi không sống được đến hôm nay.",
  "Hãy cẩn thận đừng giẫm lên bãi cỏ, tránh làm bẩn đồ ăn của tôi!",
  "Hôm nay không có tiền thì bạn cũng đừng sốt ruột, dù gì ngày mai bạn cũng không có đâu.",
  "Tôi hết tiền rồi, cũng may là sắp tới ngày nhận lương. Để xem nào… còn 29 ngày nữa thôi.",
  "Nghe nói phụ nữ thích đàn ông sạch sẽ, nên tôi nhanh trí tiêu sạch tiền.",
  "Không dám nuôi chó vì tôi sợ sẽ giành ăn với nó.",
  "Hai cách gây ô nhiễm một nơi nào đó: rác thải hoặc tiền bạc.",
  "Soi gương mà phải đóng thuế, chắc tôi sẽ phá sản.",
  "Đừng vì một ngày không có tiền mà ủ rũ. Tương lai, những ngày không có tiền còn rất nhiều.",
  "Cơ hội chỉ đến với những người đã chuẩn bị sẵn tiền.",
  "Sống ngần ấy năm, tôi từng vui, từng buồn, từng thành công, từng thất bại, nhưng chưa từng giàu.",
  "Thật kỳ cục khi phải dùng mật khẩu tận 6 số để bảo vệ số dư tài khoản chỉ có 2 số.",
  "Không có bữa ăn nào là miễn phí cả, vì thế tôi luôn ngủ tới trưa để tiết kiệm tiền ăn sáng.",
  "Không có tiền tiêu cứ nói với tôi, để tôi biết cũng có người cùng cảnh ngộ.",
  "Lương 5 triệu, nhưng số tiền tôi tiêu như thể bố tôi là đại gia.",
  "Không biết năm nay chàng trai may mắn nào sẽ có được tôi nữa. Tôi đã chuẩn bị sẵn sàng để yêu đương rồi!",
  "Tôi không nghĩ nhà em lại nghèo như thế. Tôi muốn đến chơi thì em bảo: “Không có cửa”.",
  "Valentine đến nơi rồi, cứ tỏ tình với tôi đi. Đừng ngại nhé!",
  "Nếu anh đứng bên trái, thì phải là của em.",
  "Bạn trai là gì? Có ăn được không? À, tưởng gì, mị cũng ăn rồi.",
  "Yêu đương phiền lắm, sau này đành làm phiền cậu nha.",
  "Dùng hai từ để miêu tả bạn gái của mình? - Ở đâu?",
  "Cùng nguyện bên nhau đến lúc đầu bạc, mà anh thì cạo trọc, em lại nhuộm tóc đen.",
  "Không dám hỏi anh thích kiểu con gái như thế nào, chỉ sợ rằng em hoàn toàn phù hợp.",
  "Càng ngày càng thấy mình thay đổi, trở nên giống… vợ của anh.",
  "Tôi dự định đi chơi. Mọi người biết bạn nam nào thì giới thiệu cho tôi chút?",
  "Tôi cảm giác mình có rất nhiều người yêu thầm, vì bao năm qua chẳng có một lời tỏ tình nào.",
  "Hôm qua tôi tỏ tình với em. Em nói tôi “Bị thần kinh!”. Có lẽ em sợ ảnh hưởng đến tôi nên mới nói thế. Quả là một cô gái dịu dàng!",
  "Anh rất thích trồng cây. Đó là cây si mê em.",
  "Không cần phải có nhiều người yêu, tìm 2-3 người là đủ rồi.",
  "Em yêu anh như tờ vé số, chỉ ước rằng mình trúng số phu thê.",
  "Muốn uống một cốc nước cam… kết yêu nhau trọn đời.",
  "Trúc xinh trúc mọc đầu đình. Em xinh em đứng một mình vẫn xinh.",
  "Thắng làm vua, thua làm người đẹp.",
  "Chuyện cũ không phải của biển, nên đừng đem ra khơi.",
  "Lung linh dưới ánh đèn mờ, để xem anh có phớt lờ em không.",
  "Giang hồ hiểm ác, không bằng mạng lag thất thường.",
  "Em bị cận sao? Tôi thấy em xoa kính. (“xoa kính” đọc ngược lại là “xinh quá”).",
  "Muốn tặng anh gói quà, vì nhớ anh quá gòi. (quá rồi)",
  "Vui xuân con Rồng. 0 đồng thưởng Tết.",
  "Trời sinh yếu đuối mỏng manh, nên rất cần anh ngày ngày cạnh bên.",
  "Cuộc sống quá vội vã, làm anh muốn ngã vào tim em.",
  "Người ta ai cũng có đôi, cớ sao em vẫn đơn côi một mình?",
  "Trời trở lạnh, anh chở em.",
  "Sốt thì khai báo y tế, em ế rồi biết báo ai đây?",
  "Gần mực thì đen, gần em thì dễ mến.",
  "Lúc nhỏ toàn nghịch đất nghịch cát, lớn lên toàn nghịch cảnh.",
  "Mong em mãi luôn yêu đời, tháng năm hạnh phúc chẳng rời xa em.",
  "Mưa của trời rồi cũng sẽ tạnh, tình yêu nào cũng sẽ lạnh nhanh thôi.",
  "Họ nói em rất cute. Anh yêu thì nói, đừng im re làm gì.",
  "Có ai tới được chân trời, có ai nhớ được lời từng hứa đâu.",
  "Gửi em một tấm chân tình. Tiền em không có, lấy gì tùy anh.",
  "Tướng đẹp là do tâm sinh, em đẹp là do chúng mình hợp nhau.",
  "Đôi khi không nói lời nào, chỉ đợi anh đến anh chào một câu.",
  "Em là cô gái ngoan hiền, gặp anh chỉ muốn mình liền yêu nhau.",
  "Chẳng muốn làm gì, chỉ muốn làm thinh.",
  "Xếp hàng chờ đợi đã lâu, chờ anh đến nói một câu ân tình.",
  "Văn hay chữ tốt, không bằng hốt được em xinh.",
  "Em đây không thích ngôn tình, em đây chỉ thích mỗi mình anh thôi.",
  "Phụ nữ hiện đại, không dại vì yêu.",
  "Dù ai đi ngược về xuôi, không bằng câu nói: “Anh nuôi em nè”.",
  "Ngoài đường vắng vẻ người đi, mấy nay mình cũng cần gì người yêu.",
  "Mai này vận đổi sao dời, chỉ mong em nhớ được lời hẹn chung.",
  "Muốn ăn gạo thì phải trồng lúa, muốn là công chúa thì phải yêu anh.",
  "Nghe nói em thích viết, tình cơ anh có tướng yêu thơ. (“tướng yêu thơ” đọc ngược lại thành “tớ yêu thương”)",
  "Đời nhiều cám dỗ, chỉ mong anh là bến đỗ đời em.",
  "Đăng hình cho anh ngắm, nếu say đắm thì nói yêu em.",
  "Muốn đi quẩy thì đợi đến đêm, muốn thêm em vào thì tỏ tình đi!",
  "Hôm nay trời đẹp dịu dàng, muốn đi ăn cùng nàng thì phải làm sao?",
  "Thanh xuân như một tách trà, yêu anh thêm nữa mới là thanh xuân.",
  "Mình đẹp là để mình vui, mình đẹp là để giải xui cho mình.",
  "Chị em bốn bể là nhà, sau lưng nói xấu vẫn là chị em.",
  "Chó là bạn, không phải tôi"
];